os: osx
language: swift
osx_image: xcode10
xcode_project: CISwift.xcodeproj
xcode_scheme: CISwift
script: 
  - xcodebuild clean test -project CISwift.xcodeproj -scheme CISwift -destination "platform=iOS Simulator,name=iPhone 8,OS=11.4" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
